// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Article Group documents */
interface ArticleGroupDocumentData {
    /**
     * Articles field in *Article Group*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: article_group.articles[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    articles: prismicT.GroupField<Simplify<ArticleGroupDocumentDataArticlesItem>>;
}
/**
 * Item in Article Group → Articles
 *
 */
export interface ArticleGroupDocumentDataArticlesItem {
    /**
     * article field in *Article Group → Articles*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: article_group.articles[].article
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    article: prismicT.RelationField;
}
/**
 * Article Group document from Prismic
 *
 * - **API ID**: `article_group`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArticleGroupDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<ArticleGroupDocumentData>, "article_group", Lang>;
/** Content for Author documents */
interface AuthorDocumentData {
    /**
     * Author First Name field in *Author*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: author.author_first_name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    author_first_name: prismicT.KeyTextField;
    /**
     * Author Last Name field in *Author*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: author.author_last_name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    author_last_name: prismicT.KeyTextField;
    /**
     * Author Articles field in *Author*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: author.author_articles
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    author_articles: prismicT.RelationField;
    /**
     * Author Bio field in *Author*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: author.author_bio
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    author_bio: prismicT.RichTextField;
    /**
     * Author Avatar field in *Author*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: author.author_avatar
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    author_avatar: prismicT.ImageField<never>;
}
/**
 * Author document from Prismic
 *
 * - **API ID**: `author`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AuthorDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<AuthorDocumentData>, "author", Lang>;
/** Content for Blog Collection documents */
interface BlogCollectionDocumentData {
    /**
     * Collection Name field in *Blog Collection*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_collection.collection_name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    collection_name: prismicT.KeyTextField;
    /**
     * Collection Image field in *Blog Collection*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_collection.collection_image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    collection_image: prismicT.ImageField<never>;
    /**
     * Collection Articles field in *Blog Collection*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_collection.collection_articles
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    collection_articles: prismicT.RelationField;
    /**
     * Collection SEO Description field in *Blog Collection*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_collection.collection_seo_description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    collection_seo_description: prismicT.KeyTextField;
    /**
     * Parent collection field in *Blog Collection*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_collection.collection
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    collection: prismicT.RelationField<"collection">;
}
/**
 * Blog Collection document from Prismic
 *
 * - **API ID**: `blog_collection`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogCollectionDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<BlogCollectionDocumentData>, "blog_collection", Lang>;
/** Content for Blog Post documents */
interface BlogPostDocumentData {
    /**
     * Article image field in *Blog Post*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_post.article_cover
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    article_cover: prismicT.ImageField<never>;
    /**
     * Article title field in *Blog Post*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_post.article_title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    article_title: prismicT.KeyTextField;
    /**
     * Article content field in *Blog Post*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Hello, la Guadeloupe est magnifique
     * - **API ID Path**: blog_post.article_content
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    article_content: prismicT.RichTextField;
    /**
     * Article author field in *Blog Post*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_post.article_author
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    article_author: prismicT.RelationField<"author">;
    /**
     * Preview field in *Blog Post*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Article prieview...
     * - **API ID Path**: blog_post.preview
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    preview: prismicT.KeyTextField;
    /**
     * Parent category field in *Blog Post*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_post.category
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    category: prismicT.RelationField<"blog_collection">;
}
/**
 * Blog Post document from Prismic
 *
 * - **API ID**: `blog_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<BlogPostDocumentData>, "blog_post", Lang>;
/** Content for Category documents */
interface CategoryDocumentData {
    /**
     * Category Image field in *Category*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: category.category_image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    category_image: prismicT.ImageField<never>;
    /**
     * Category articles field in *Category*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: category.category_articles
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    category_articles: prismicT.RelationField<"blog_post">;
    /**
     * Category collections field in *Category*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: category.category_collections
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    category_collections: prismicT.RelationField<"category">;
    /**
     * SEO description field in *Category*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: category.category_seo_description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    category_seo_description: prismicT.RichTextField;
    /**
     * Category description field in *Category*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: category.category_description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    category_description: prismicT.RichTextField;
}
/**
 * Category document from Prismic
 *
 * - **API ID**: `category`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CategoryDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<CategoryDocumentData>, "category", Lang>;
/** Content for Collection documents */
interface CollectionDocumentData {
    /**
     * Categories field in *Collection*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: collection.categories[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    categories: prismicT.GroupField<Simplify<CollectionDocumentDataCategoriesItem>>;
    /**
     * Other Articles field in *Collection*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: collection.other_articles[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    other_articles: prismicT.GroupField<Simplify<CollectionDocumentDataOtherArticlesItem>>;
    /**
     * Slice Zone field in *Collection*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: collection.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<CollectionDocumentDataSlicesSlice>;
}
/**
 * Item in Collection → Categories
 *
 */
export interface CollectionDocumentDataCategoriesItem {
    /**
     * Category field in *Collection → Categories*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: collection.categories[].category
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    category: prismicT.RelationField;
}
/**
 * Item in Collection → Other Articles
 *
 */
export interface CollectionDocumentDataOtherArticlesItem {
    /**
     * Blog article field in *Collection → Other Articles*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: collection.other_articles[].blog_article
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    blog_article: prismicT.RelationField;
}
/**
 * Slice for *Collection → Slice Zone*
 *
 */
type CollectionDocumentDataSlicesSlice = never;
/**
 * Collection document from Prismic
 *
 * - **API ID**: `collection`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CollectionDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<CollectionDocumentData>, "collection", Lang>;
/** Content for Footer documents */
interface FooterDocumentData {
    /**
     * Menu about field in *Footer*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.menu_about
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    menu_about: prismicT.RelationField<"navigation_menu">;
    /**
     * Menu SEO field in *Footer*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.menu_seo
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    menu_seo: prismicT.RelationField<"navigation_menu">;
    /**
     * Newsletter header field in *Footer*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.newsletter_header
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    newsletter_header: prismicT.RichTextField;
    /**
     * Newsletter description field in *Footer*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.newsletter_description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    newsletter_description: prismicT.RichTextField;
    /**
     * Socials field in *Footer*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.socials
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    socials: prismicT.RelationField<"socials">;
    /**
     * Background color field in *Footer*
     *
     * - **Field Type**: Color
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.background_color
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/color
     *
     */
    background_color: prismicT.ColorField;
    /**
     * Text color field in *Footer*
     *
     * - **Field Type**: Color
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.text_color
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/color
     *
     */
    text_color: prismicT.ColorField;
    /**
     * Input border field in *Footer*
     *
     * - **Field Type**: Color
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.input_border
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/color
     *
     */
    input_border: prismicT.ColorField;
    /**
     * Input btn bg field in *Footer*
     *
     * - **Field Type**: Color
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.input_btn_bg
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/color
     *
     */
    input_btn_bg: prismicT.ColorField;
    /**
     * Input text field in *Footer*
     *
     * - **Field Type**: Color
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.input_text
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/color
     *
     */
    input_text: prismicT.ColorField;
    /**
     * Slice Zone field in *Footer*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<FooterDocumentDataSlicesSlice>;
}
/**
 * Slice for *Footer → Slice Zone*
 *
 */
type FooterDocumentDataSlicesSlice = never;
/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<FooterDocumentData>, "footer", Lang>;
/** Content for Homepage documents */
interface HomepageDocumentData {
    /**
     * Hero Image field in *Homepage*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.hero_image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    hero_image: prismicT.ImageField<never>;
    /**
     * Home Collections field in *Homepage*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.home_collections
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    home_collections: prismicT.RelationField;
    /**
     * Home SEO Description field in *Homepage*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.home_seo_description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    home_seo_description: prismicT.KeyTextField;
    /**
     * Home Promo Banner field in *Homepage*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.home_promo_banner
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    home_promo_banner: prismicT.ImageField<never>;
    /**
     * Home SEO Text Block field in *Homepage*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.home_seo_text_block
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    home_seo_text_block: prismicT.RichTextField;
    /**
     * Slice Zone field in *Homepage*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<HomepageDocumentDataSlicesSlice>;
}
/**
 * Slice for *Homepage → Slice Zone*
 *
 */
type HomepageDocumentDataSlicesSlice = HomeHeroSlice | MixedGridSlice | VanityHeroSlice | CollectionGridSlice | TopStorySlice;
/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<HomepageDocumentData>, "homepage", Lang>;
/** Content for Navbar documents */
interface NavbarDocumentData {
    /**
     * Slice Zone field in *Navbar*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: navbar.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<NavbarDocumentDataSlicesSlice>;
}
/**
 * Slice for *Navbar → Slice Zone*
 *
 */
type NavbarDocumentDataSlicesSlice = NavbarSlice;
/**
 * Navbar document from Prismic
 *
 * - **API ID**: `navbar`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavbarDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<NavbarDocumentData>, "navbar", Lang>;
/** Content for Menu Navigation documents */
interface NavigationMenuDocumentData {
    /**
     * Menu field in *Menu Navigation*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation_menu.menu[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    menu: prismicT.GroupField<Simplify<NavigationMenuDocumentDataMenuItem>>;
    /**
     * Title field in *Menu Navigation*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Entrer le titre du menu
     * - **API ID Path**: navigation_menu.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.RichTextField;
}
/**
 * Item in Menu Navigation → Menu
 *
 */
export interface NavigationMenuDocumentDataMenuItem {
    /**
     * Link field in *Menu Navigation → Menu*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation_menu.menu[].link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link: prismicT.LinkField;
    /**
     * Text field in *Menu Navigation → Menu*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation_menu.menu[].text
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    text: prismicT.KeyTextField;
}
/**
 * Menu Navigation document from Prismic
 *
 * - **API ID**: `navigation_menu`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationMenuDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<NavigationMenuDocumentData>, "navigation_menu", Lang>;
/** Content for Navigation documents */
interface NavigationDocumentData {
    /**
     * Navigation Item field in *Navigation*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.navigation_item[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    navigation_item: prismicT.GroupField<Simplify<NavigationDocumentDataNavigationItemItem>>;
}
/**
 * Item in Navigation → Navigation Item
 *
 */
export interface NavigationDocumentDataNavigationItemItem {
    /**
     * Item Name field in *Navigation → Navigation Item*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.navigation_item[].item_name
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    item_name: prismicT.KeyTextField;
    /**
     * Item Link field in *Navigation → Navigation Item*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.navigation_item[].item_link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    item_link: prismicT.LinkField;
    /**
     * Item Icon field in *Navigation → Navigation Item*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.navigation_item[].item_icon
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    item_icon: prismicT.ImageField<never>;
}
/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<NavigationDocumentData>, "navigation", Lang>;
/** Content for Page documents */
interface PageDocumentData {
    /**
     * category field in *Page*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: page.category
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    category: prismicT.RelationField<"blog_collection">;
    /**
     * Page SEO Description field in *Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.page_seo_description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    page_seo_description: prismicT.KeyTextField;
    /**
     * Page Collections field in *Page*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: page.page_collections
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    page_collections: prismicT.RelationField;
    /**
     * Page Text Block field in *Page*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.page_rich_text_block
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    page_rich_text_block: prismicT.RichTextField;
    /**
     * Page Promo Banner field in *Page*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: page.page_promo_banner
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    page_promo_banner: prismicT.ImageField<never>;
    /**
     * Page SEO Title field in *Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.page_seo_title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    page_seo_title: prismicT.KeyTextField;
}
/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;
/** Content for Socials documents */
interface SocialsDocumentData {
    /**
     * Media Info field in *Socials*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: socials.media_info[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    media_info: prismicT.GroupField<Simplify<SocialsDocumentDataMediaInfoItem>>;
    /**
     * CTA field in *Socials*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: socials.cta
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    cta: prismicT.KeyTextField;
}
/**
 * Item in Socials → Media Info
 *
 */
export interface SocialsDocumentDataMediaInfoItem {
    /**
     * Social Media field in *Socials → Media Info*
     *
     * - **Field Type**: Select
     * - **Placeholder**: Select the social media
     * - **API ID Path**: socials.media_info[].social_media
     * - **Documentation**: https://prismic.io/docs/core-concepts/select
     *
     */
    social_media: prismicT.SelectField<"Instagram" | "Pinterest" | "Email" | "TikTok">;
    /**
     * Social link field in *Socials → Media Info*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: socials.media_info[].social_link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    social_link: prismicT.LinkField;
}
/**
 * Socials document from Prismic
 *
 * - **API ID**: `socials`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SocialsDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<SocialsDocumentData>, "socials", Lang>;
/** Content for Vanity Promo documents */
interface VanitySponsoringDocumentData {
    /**
     * Promo text field in *Vanity Promo*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: vanity_sponsoring.promo_text
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    promo_text: prismicT.KeyTextField;
    /**
     * Promo img field in *Vanity Promo*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: vanity_sponsoring.promo_img
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    promo_img: prismicT.ImageField<never>;
    /**
     * Promo link field in *Vanity Promo*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: vanity_sponsoring.promo_link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    promo_link: prismicT.LinkField;
    /**
     * Promo CTA text field in *Vanity Promo*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: vanity_sponsoring.promo_cta_text
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    promo_cta_text: prismicT.KeyTextField;
}
/**
 * Vanity Promo document from Prismic
 *
 * - **API ID**: `vanity_sponsoring`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type VanitySponsoringDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<VanitySponsoringDocumentData>, "vanity_sponsoring", Lang>;
/** Content for Vanity Socials documents */
interface VanitysocialpostsDocumentData {
    /**
     * Post field in *Vanity Socials*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: vanitysocialposts.post[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    post: prismicT.GroupField<Simplify<VanitysocialpostsDocumentDataPostItem>>;
    /**
     * Title field in *Vanity Socials*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: vanitysocialposts.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Slice Zone field in *Vanity Socials*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: vanitysocialposts.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<VanitysocialpostsDocumentDataSlicesSlice>;
}
/**
 * Item in Vanity Socials → Post
 *
 */
export interface VanitysocialpostsDocumentDataPostItem {
    /**
     * PostImg field in *Vanity Socials → Post*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: vanitysocialposts.post[].postimg
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    postimg: prismicT.ImageField<never>;
    /**
     * Postlink field in *Vanity Socials → Post*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: vanitysocialposts.post[].postlink
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    postlink: prismicT.LinkField;
}
/**
 * Slice for *Vanity Socials → Slice Zone*
 *
 */
type VanitysocialpostsDocumentDataSlicesSlice = never;
/**
 * Vanity Socials document from Prismic
 *
 * - **API ID**: `vanitysocialposts`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type VanitysocialpostsDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<VanitysocialpostsDocumentData>, "vanitysocialposts", Lang>;
export type AllDocumentTypes = ArticleGroupDocument | AuthorDocument | BlogCollectionDocument | BlogPostDocument | CategoryDocument | CollectionDocument | FooterDocument | HomepageDocument | NavbarDocument | NavigationMenuDocument | NavigationDocument | PageDocument | SocialsDocument | VanitySponsoringDocument | VanitysocialpostsDocument;
/**
 * Primary content in CollectionGrid → Primary
 *
 */
interface CollectionGridSliceDefaultPrimary {
    /**
     * Collection uid field in *CollectionGrid → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: Select the tag for this collection
     * - **API ID Path**: collection_grid.primary.collection_uid
     * - **Documentation**: https://prismic.io/docs/core-concepts/select
     *
     */
    collection_uid: prismicT.SelectField<"que faire?" | "ou manger?" | "ou loger?">;
    /**
     * Collection title field in *CollectionGrid → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: collection_grid.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
}
/**
 * Default variation for CollectionGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: `CollectionGrid`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CollectionGridSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<CollectionGridSliceDefaultPrimary>, never>;
/**
 * Slice variation for *CollectionGrid*
 *
 */
type CollectionGridSliceVariation = CollectionGridSliceDefault;
/**
 * CollectionGrid Shared Slice
 *
 * - **API ID**: `collection_grid`
 * - **Description**: `CollectionGrid`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CollectionGridSlice = prismicT.SharedSlice<"collection_grid", CollectionGridSliceVariation>;
/**
 * Primary content in Footer → Primary
 *
 */
interface FooterSliceDefaultPrimary {
    /**
     * Background Color field in *Footer → Primary*
     *
     * - **Field Type**: Color
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.primary.background_color
     * - **Documentation**: https://prismic.io/docs/core-concepts/color
     *
     */
    background_color: prismicT.ColorField;
    /**
     * Text Color field in *Footer → Primary*
     *
     * - **Field Type**: Color
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.primary.text_color
     * - **Documentation**: https://prismic.io/docs/core-concepts/color
     *
     */
    text_color: prismicT.ColorField;
    /**
     * Menu about field in *Footer → Primary*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.primary.menu_about
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    menu_about: prismicT.RelationField<"navigation_menu">;
    /**
     * Menu_seo field in *Footer → Primary*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.primary.menu_seo
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    menu_seo: prismicT.RelationField<"navigation_menu">;
    /**
     * Newsletter Header field in *Footer → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.primary.newsletter_header
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    newsletter_header: prismicT.RichTextField;
    /**
     * Newsletter description field in *Footer → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.primary.newsletter_description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    newsletter_description: prismicT.RichTextField;
    /**
     * Socials field in *Footer → Primary*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.primary.socials
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    socials: prismicT.RelationField<"socials">;
    /**
     * Input border field in *Footer → Primary*
     *
     * - **Field Type**: Color
     * - **Placeholder**: Select input border color
     * - **API ID Path**: footer.primary.input_border_color
     * - **Documentation**: https://prismic.io/docs/core-concepts/color
     *
     */
    input_border_color: prismicT.ColorField;
    /**
     * Input btn bg field in *Footer → Primary*
     *
     * - **Field Type**: Color
     * - **Placeholder**: Select the button background color
     * - **API ID Path**: footer.primary.input_btn_bg_color
     * - **Documentation**: https://prismic.io/docs/core-concepts/color
     *
     */
    input_btn_bg_color: prismicT.ColorField;
    /**
     * Input text field in *Footer → Primary*
     *
     * - **Field Type**: Color
     * - **Placeholder**: Select input text color
     * - **API ID Path**: footer.primary.input_text_input_color
     * - **Documentation**: https://prismic.io/docs/core-concepts/color
     *
     */
    input_text_input_color: prismicT.ColorField;
}
/**
 * Default variation for Footer Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Footer`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FooterSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<FooterSliceDefaultPrimary>, never>;
/**
 * Slice variation for *Footer*
 *
 */
type FooterSliceVariation = FooterSliceDefault;
/**
 * Footer Shared Slice
 *
 * - **API ID**: `footer`
 * - **Description**: `Footer`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FooterSlice = prismicT.SharedSlice<"footer", FooterSliceVariation>;
/**
 * Primary content in HomeHero → Primary
 *
 */
interface HomeHeroSliceDefaultPrimary {
    /**
     * Header field in *HomeHero → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: A nice header for your hero
     * - **API ID Path**: home_hero.primary.header
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    header: prismicT.TitleField;
    /**
     * Subtitle field in *HomeHero → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice subtitle for the homepage
     * - **API ID Path**: home_hero.primary.subheader
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    subheader: prismicT.RichTextField;
    /**
     * Video field in *HomeHero → Primary*
     *
     * - **Field Type**: Link to Media
     * - **Placeholder**: Paste link to video here...
     * - **API ID Path**: home_hero.primary.hero_video
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    hero_video: prismicT.LinkToMediaField;
    /**
     * navigation field in *HomeHero → Primary*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: home_hero.primary.navigation
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    navigation: prismicT.RelationField<"navigation">;
    /**
     * Logo field in *HomeHero → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: home_hero.primary.logo
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    logo: prismicT.ImageField<never>;
    /**
     * Opacity Color field in *HomeHero → Primary*
     *
     * - **Field Type**: Color
     * - **Placeholder**: *None*
     * - **API ID Path**: home_hero.primary.opacity_color
     * - **Documentation**: https://prismic.io/docs/core-concepts/color
     *
     */
    opacity_color: prismicT.ColorField;
    /**
     * Opacity Percentage field in *HomeHero → Primary*
     *
     * - **Field Type**: Number
     * - **Placeholder**: *None*
     * - **API ID Path**: home_hero.primary.opacity_percentage
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    opacity_percentage: prismicT.NumberField;
}
/**
 * Default variation for HomeHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: `HomeHero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HomeHeroSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<HomeHeroSliceDefaultPrimary>, never>;
/**
 * Slice variation for *HomeHero*
 *
 */
type HomeHeroSliceVariation = HomeHeroSliceDefault;
/**
 * HomeHero Shared Slice
 *
 * - **API ID**: `home_hero`
 * - **Description**: `HomeHero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HomeHeroSlice = prismicT.SharedSlice<"home_hero", HomeHeroSliceVariation>;
/**
 * Primary content in MixedGrid → Primary
 *
 */
interface MixedGridSliceDefaultPrimary {
    /**
     * Title field in *MixedGrid → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: mixed_grid.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description field in *MixedGrid → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: mixed_grid.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * Main Article field in *MixedGrid → Primary*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: mixed_grid.primary.main_article
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    main_article: prismicT.RelationField<"blog_post">;
}
/**
 * Item in MixedGrid → Items
 *
 */
export interface MixedGridSliceDefaultItem {
    /**
     * Other Articles field in *MixedGrid → Items*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: mixed_grid.items[].article
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    article: prismicT.RelationField<"blog_post">;
}
/**
 * Default variation for MixedGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: `MixedGrid`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type MixedGridSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<MixedGridSliceDefaultPrimary>, Simplify<MixedGridSliceDefaultItem>>;
/**
 * Slice variation for *MixedGrid*
 *
 */
type MixedGridSliceVariation = MixedGridSliceDefault;
/**
 * MixedGrid Shared Slice
 *
 * - **API ID**: `mixed_grid`
 * - **Description**: `MixedGrid`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type MixedGridSlice = prismicT.SharedSlice<"mixed_grid", MixedGridSliceVariation>;
/**
 * Primary content in Navbar → Primary
 *
 */
interface NavbarSliceDefaultPrimary {
    /**
     * Navigation field in *Navbar → Primary*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: navbar.primary.navigation
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    navigation: prismicT.RelationField<"navigation">;
    /**
     * Logo field in *Navbar → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: navbar.primary.logo
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    logo: prismicT.ImageField<never>;
}
/**
 * Default variation for Navbar Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Navbar`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type NavbarSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<NavbarSliceDefaultPrimary>, never>;
/**
 * Slice variation for *Navbar*
 *
 */
type NavbarSliceVariation = NavbarSliceDefault;
/**
 * Navbar Shared Slice
 *
 * - **API ID**: `navbar`
 * - **Description**: `Navbar`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type NavbarSlice = prismicT.SharedSlice<"navbar", NavbarSliceVariation>;
/**
 * Primary content in TopStory → Primary
 *
 */
interface TopStorySliceDefaultPrimary {
    /**
     * Main article field in *TopStory → Primary*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: top_story.primary.main_article
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    main_article: prismicT.RelationField<"blog_post">;
    /**
     * Title field in *TopStory → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Enter the section's title
     * - **API ID Path**: top_story.primary.section_title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    section_title: prismicT.KeyTextField;
}
/**
 * Item in TopStory → Items
 *
 */
export interface TopStorySliceDefaultItem {
    /**
     * Other articles (4 max) field in *TopStory → Items*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: top_story.items[].other_articles
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    other_articles: prismicT.RelationField<"blog_post">;
}
/**
 * Default variation for TopStory Slice
 *
 * - **API ID**: `default`
 * - **Description**: `TopStory`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TopStorySliceDefault = prismicT.SharedSliceVariation<"default", Simplify<TopStorySliceDefaultPrimary>, Simplify<TopStorySliceDefaultItem>>;
/**
 * Slice variation for *TopStory*
 *
 */
type TopStorySliceVariation = TopStorySliceDefault;
/**
 * TopStory Shared Slice
 *
 * - **API ID**: `top_story`
 * - **Description**: `TopStory`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TopStorySlice = prismicT.SharedSlice<"top_story", TopStorySliceVariation>;
/**
 * Primary content in VanityHero → Primary
 *
 */
interface VanityHeroSliceDefaultPrimary {
    /**
     * Main article field in *VanityHero → Primary*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: vanity_hero.primary.main_article
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    main_article: prismicT.RelationField<"blog_post">;
    /**
     * Social Posts (4 posts) field in *VanityHero → Primary*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: vanity_hero.primary.social_posts
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    social_posts: prismicT.RelationField<"vanitysocialposts">;
    /**
     * Socials Accounts field in *VanityHero → Primary*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: vanity_hero.primary.socials_accounts
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    socials_accounts: prismicT.RelationField<"socials">;
    /**
     * Promo field in *VanityHero → Primary*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: vanity_hero.primary.promo
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    promo: prismicT.RelationField<"vanity_sponsoring">;
}
/**
 * Item in VanityHero → Items
 *
 */
export interface VanityHeroSliceDefaultItem {
    /**
     * Trending articles (3 articles) field in *VanityHero → Items*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: vanity_hero.items[].trending_articles
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    trending_articles: prismicT.RelationField<"blog_post">;
    /**
     * Other articles (2 articles) field in *VanityHero → Items*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: vanity_hero.items[].other_articles
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    other_articles: prismicT.RelationField<"blog_post">;
}
/**
 * Default variation for VanityHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: `VanityHero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type VanityHeroSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<VanityHeroSliceDefaultPrimary>, Simplify<VanityHeroSliceDefaultItem>>;
/**
 * Slice variation for *VanityHero*
 *
 */
type VanityHeroSliceVariation = VanityHeroSliceDefault;
/**
 * VanityHero Shared Slice
 *
 * - **API ID**: `vanity_hero`
 * - **Description**: `VanityHero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type VanityHeroSlice = prismicT.SharedSlice<"vanity_hero", VanityHeroSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { ArticleGroupDocumentData, ArticleGroupDocumentDataArticlesItem, ArticleGroupDocument, AuthorDocumentData, AuthorDocument, BlogCollectionDocumentData, BlogCollectionDocument, BlogPostDocumentData, BlogPostDocument, CategoryDocumentData, CategoryDocument, CollectionDocumentData, CollectionDocumentDataCategoriesItem, CollectionDocumentDataOtherArticlesItem, CollectionDocumentDataSlicesSlice, CollectionDocument, FooterDocumentData, FooterDocumentDataSlicesSlice, FooterDocument, HomepageDocumentData, HomepageDocumentDataSlicesSlice, HomepageDocument, NavbarDocumentData, NavbarDocumentDataSlicesSlice, NavbarDocument, NavigationMenuDocumentData, NavigationMenuDocumentDataMenuItem, NavigationMenuDocument, NavigationDocumentData, NavigationDocumentDataNavigationItemItem, NavigationDocument, PageDocumentData, PageDocument, SocialsDocumentData, SocialsDocumentDataMediaInfoItem, SocialsDocument, VanitySponsoringDocumentData, VanitySponsoringDocument, VanitysocialpostsDocumentData, VanitysocialpostsDocumentDataPostItem, VanitysocialpostsDocumentDataSlicesSlice, VanitysocialpostsDocument, AllDocumentTypes, CollectionGridSliceDefaultPrimary, CollectionGridSliceDefault, CollectionGridSliceVariation, CollectionGridSlice, FooterSliceDefaultPrimary, FooterSliceDefault, FooterSliceVariation, FooterSlice, HomeHeroSliceDefaultPrimary, HomeHeroSliceDefault, HomeHeroSliceVariation, HomeHeroSlice, MixedGridSliceDefaultPrimary, MixedGridSliceDefaultItem, MixedGridSliceDefault, MixedGridSliceVariation, MixedGridSlice, NavbarSliceDefaultPrimary, NavbarSliceDefault, NavbarSliceVariation, NavbarSlice, TopStorySliceDefaultPrimary, TopStorySliceDefaultItem, TopStorySliceDefault, TopStorySliceVariation, TopStorySlice, VanityHeroSliceDefaultPrimary, VanityHeroSliceDefaultItem, VanityHeroSliceDefault, VanityHeroSliceVariation, VanityHeroSlice };
    }
}
