// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Author documents */
interface AuthorDocumentData {
    /**
     * Author First Name field in *Author*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: author.author_first_name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    author_first_name: prismicT.KeyTextField;
    /**
     * Author Last Name field in *Author*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: author.author_last_name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    author_last_name: prismicT.KeyTextField;
    /**
     * Author Articles field in *Author*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: author.author_articles
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    author_articles: prismicT.RelationField;
    /**
     * Author Bio field in *Author*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: author.author_bio
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    author_bio: prismicT.RichTextField;
    /**
     * Author Avatar field in *Author*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: author.author_avatar
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    author_avatar: prismicT.ImageField<never>;
}
/**
 * Author document from Prismic
 *
 * - **API ID**: `author`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AuthorDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<AuthorDocumentData>, "author", Lang>;
/** Content for Blog Post documents */
interface BlogPostDocumentData {
    /**
     * Article image field in *Blog Post*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_post.article_cover
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    article_cover: prismicT.ImageField<never>;
    /**
     * Article title field in *Blog Post*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_post.article_title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    article_title: prismicT.KeyTextField;
    /**
     * Article content field in *Blog Post*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Hello, la Guadeloupe est magnifique
     * - **API ID Path**: blog_post.article_content
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    article_content: prismicT.RichTextField;
    /**
     * Article author field in *Blog Post*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_post.article_author
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    article_author: prismicT.RelationField<"author">;
    /**
     * Preview field in *Blog Post*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Article prieview...
     * - **API ID Path**: blog_post.preview
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    preview: prismicT.KeyTextField;
}
/**
 * Blog Post document from Prismic
 *
 * - **API ID**: `blog_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<BlogPostDocumentData>, "blog_post", Lang>;
/** Content for Collection documents */
interface CollectionDocumentData {
    /**
     * Title field in *Collection*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: collection.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Image field in *Collection*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: collection.image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
}
/**
 * Collection document from Prismic
 *
 * - **API ID**: `collection`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CollectionDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<CollectionDocumentData>, "collection", Lang>;
/** Content for Footer documents */
interface FooterDocumentData {
    /**
     * Menu about field in *Footer*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.menu_about
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    menu_about: prismicT.RelationField<"navigation_menu">;
    /**
     * Menu SEO field in *Footer*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.menu_seo
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    menu_seo: prismicT.RelationField<"navigation_menu">;
    /**
     * Newsletter header field in *Footer*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.newsletter_header
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    newsletter_header: prismicT.RichTextField;
    /**
     * Newsletter description field in *Footer*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.newsletter_description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    newsletter_description: prismicT.RichTextField;
    /**
     * Socials field in *Footer*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.socials
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    socials: prismicT.RelationField<"socials">;
    /**
     * Background color field in *Footer*
     *
     * - **Field Type**: Color
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.background_color
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/color
     *
     */
    background_color: prismicT.ColorField;
    /**
     * Text color field in *Footer*
     *
     * - **Field Type**: Color
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.text_color
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/color
     *
     */
    text_color: prismicT.ColorField;
    /**
     * Input border field in *Footer*
     *
     * - **Field Type**: Color
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.input_border
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/color
     *
     */
    input_border: prismicT.ColorField;
    /**
     * Input btn bg field in *Footer*
     *
     * - **Field Type**: Color
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.input_btn_bg
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/color
     *
     */
    input_btn_bg: prismicT.ColorField;
    /**
     * Input text field in *Footer*
     *
     * - **Field Type**: Color
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.input_text
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/color
     *
     */
    input_text: prismicT.ColorField;
    /**
     * Slice Zone field in *Footer*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<FooterDocumentDataSlicesSlice>;
}
/**
 * Slice for *Footer → Slice Zone*
 *
 */
type FooterDocumentDataSlicesSlice = never;
/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<FooterDocumentData>, "footer", Lang>;
/** Content for Homepage documents */
interface HomepageDocumentData {
    /**
     * Slice Zone field in *Homepage*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<HomepageDocumentDataSlicesSlice>;
}
/**
 * Slice for *Homepage → Slice Zone*
 *
 */
type HomepageDocumentDataSlicesSlice = HomeHeroSlice | MixedGridSlice | VanityHeroSlice | CollectionGridSlice | TopStorySlice | CollectionSliderSlice | FeaturedArticleSlice | VideoHeroSlice;
/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<HomepageDocumentData>, "homepage", Lang>;
/** Content for Navbar documents */
interface NavbarDocumentData {
    /**
     * Slice Zone field in *Navbar*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: navbar.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<NavbarDocumentDataSlicesSlice>;
}
/**
 * Slice for *Navbar → Slice Zone*
 *
 */
type NavbarDocumentDataSlicesSlice = NavbarSlice;
/**
 * Navbar document from Prismic
 *
 * - **API ID**: `navbar`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavbarDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<NavbarDocumentData>, "navbar", Lang>;
/** Content for Menu Navigation documents */
interface NavigationMenuDocumentData {
    /**
     * Menu field in *Menu Navigation*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation_menu.menu[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    menu: prismicT.GroupField<Simplify<NavigationMenuDocumentDataMenuItem>>;
    /**
     * Title field in *Menu Navigation*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Entrer le titre du menu
     * - **API ID Path**: navigation_menu.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.RichTextField;
}
/**
 * Item in Menu Navigation → Menu
 *
 */
export interface NavigationMenuDocumentDataMenuItem {
    /**
     * Link field in *Menu Navigation → Menu*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation_menu.menu[].link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link: prismicT.LinkField;
    /**
     * Text field in *Menu Navigation → Menu*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation_menu.menu[].text
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    text: prismicT.KeyTextField;
}
/**
 * Menu Navigation document from Prismic
 *
 * - **API ID**: `navigation_menu`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationMenuDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<NavigationMenuDocumentData>, "navigation_menu", Lang>;
/** Content for Navigation documents */
interface NavigationDocumentData {
    /**
     * Navigation Item field in *Navigation*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.navigation_item[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    navigation_item: prismicT.GroupField<Simplify<NavigationDocumentDataNavigationItemItem>>;
}
/**
 * Item in Navigation → Navigation Item
 *
 */
export interface NavigationDocumentDataNavigationItemItem {
    /**
     * Item Name field in *Navigation → Navigation Item*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.navigation_item[].item_name
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    item_name: prismicT.KeyTextField;
    /**
     * Item Link field in *Navigation → Navigation Item*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.navigation_item[].item_link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    item_link: prismicT.LinkField;
    /**
     * Item Icon field in *Navigation → Navigation Item*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.navigation_item[].item_icon
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    item_icon: prismicT.ImageField<never>;
}
/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<NavigationDocumentData>, "navigation", Lang>;
/** Content for Page documents */
type PageDocumentData = Record<string, never>;
/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;
/** Content for Socials documents */
interface SocialsDocumentData {
    /**
     * Media Info field in *Socials*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: socials.media_info[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    media_info: prismicT.GroupField<Simplify<SocialsDocumentDataMediaInfoItem>>;
    /**
     * CTA field in *Socials*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: socials.cta
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    cta: prismicT.KeyTextField;
}
/**
 * Item in Socials → Media Info
 *
 */
export interface SocialsDocumentDataMediaInfoItem {
    /**
     * Social Media field in *Socials → Media Info*
     *
     * - **Field Type**: Select
     * - **Placeholder**: Select the social media
     * - **API ID Path**: socials.media_info[].social_media
     * - **Documentation**: https://prismic.io/docs/core-concepts/select
     *
     */
    social_media: prismicT.SelectField<"Instagram" | "Pinterest" | "Email" | "TikTok">;
    /**
     * Social link field in *Socials → Media Info*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: socials.media_info[].social_link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    social_link: prismicT.LinkField;
}
/**
 * Socials document from Prismic
 *
 * - **API ID**: `socials`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SocialsDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<SocialsDocumentData>, "socials", Lang>;
/** Content for Vanity Promo documents */
interface VanitySponsoringDocumentData {
    /**
     * Promo text field in *Vanity Promo*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: vanity_sponsoring.promo_text
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    promo_text: prismicT.KeyTextField;
    /**
     * Promo img field in *Vanity Promo*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: vanity_sponsoring.promo_img
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    promo_img: prismicT.ImageField<never>;
    /**
     * Promo link field in *Vanity Promo*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: vanity_sponsoring.promo_link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    promo_link: prismicT.LinkField;
    /**
     * Promo CTA text field in *Vanity Promo*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: vanity_sponsoring.promo_cta_text
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    promo_cta_text: prismicT.KeyTextField;
}
/**
 * Vanity Promo document from Prismic
 *
 * - **API ID**: `vanity_sponsoring`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type VanitySponsoringDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<VanitySponsoringDocumentData>, "vanity_sponsoring", Lang>;
/** Content for Vanity Socials documents */
interface VanitysocialpostsDocumentData {
    /**
     * Post field in *Vanity Socials*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: vanitysocialposts.post[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    post: prismicT.GroupField<Simplify<VanitysocialpostsDocumentDataPostItem>>;
    /**
     * Title field in *Vanity Socials*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: vanitysocialposts.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Slice Zone field in *Vanity Socials*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: vanitysocialposts.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<VanitysocialpostsDocumentDataSlicesSlice>;
}
/**
 * Item in Vanity Socials → Post
 *
 */
export interface VanitysocialpostsDocumentDataPostItem {
    /**
     * PostImg field in *Vanity Socials → Post*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: vanitysocialposts.post[].postimg
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    postimg: prismicT.ImageField<never>;
    /**
     * Postlink field in *Vanity Socials → Post*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: vanitysocialposts.post[].postlink
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    postlink: prismicT.LinkField;
}
/**
 * Slice for *Vanity Socials → Slice Zone*
 *
 */
type VanitysocialpostsDocumentDataSlicesSlice = never;
/**
 * Vanity Socials document from Prismic
 *
 * - **API ID**: `vanitysocialposts`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type VanitysocialpostsDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<VanitysocialpostsDocumentData>, "vanitysocialposts", Lang>;
export type AllDocumentTypes = AuthorDocument | BlogPostDocument | CollectionDocument | FooterDocument | HomepageDocument | NavbarDocument | NavigationMenuDocument | NavigationDocument | PageDocument | SocialsDocument | VanitySponsoringDocument | VanitysocialpostsDocument;
/**
 * Primary content in CollectionGrid → Primary
 *
 */
interface CollectionGridSliceDefaultPrimary {
    /**
     * Collection uid field in *CollectionGrid → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: Select the tag for this collection
     * - **API ID Path**: collection_grid.primary.collection_uid
     * - **Documentation**: https://prismic.io/docs/core-concepts/select
     *
     */
    collection_uid: prismicT.SelectField<"que faire?" | "ou manger?" | "ou loger?">;
    /**
     * Collection title field in *CollectionGrid → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: collection_grid.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
}
/**
 * Default variation for CollectionGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: `CollectionGrid`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CollectionGridSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<CollectionGridSliceDefaultPrimary>, never>;
/**
 * Slice variation for *CollectionGrid*
 *
 */
type CollectionGridSliceVariation = CollectionGridSliceDefault;
/**
 * CollectionGrid Shared Slice
 *
 * - **API ID**: `collection_grid`
 * - **Description**: `CollectionGrid`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CollectionGridSlice = prismicT.SharedSlice<"collection_grid", CollectionGridSliceVariation>;
/**
 * Primary content in CollectionSlider → Primary
 *
 */
interface CollectionSliderSliceDefaultPrimary {
    /**
     * Title field in *CollectionSlider → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: collection_slider.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
}
/**
 * Item in CollectionSlider → Items
 *
 */
export interface CollectionSliderSliceDefaultItem {
    /**
     * Collection field in *CollectionSlider → Items*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: collection_slider.items[].collection
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    collection: prismicT.RelationField<"collection">;
}
/**
 * Default variation for CollectionSlider Slice
 *
 * - **API ID**: `default`
 * - **Description**: `CollectionSlider`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CollectionSliderSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<CollectionSliderSliceDefaultPrimary>, Simplify<CollectionSliderSliceDefaultItem>>;
/**
 * Slice variation for *CollectionSlider*
 *
 */
type CollectionSliderSliceVariation = CollectionSliderSliceDefault;
/**
 * CollectionSlider Shared Slice
 *
 * - **API ID**: `collection_slider`
 * - **Description**: `CollectionSlider`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CollectionSliderSlice = prismicT.SharedSlice<"collection_slider", CollectionSliderSliceVariation>;
/**
 * Primary content in FeaturedArticle → Primary
 *
 */
interface FeaturedArticleSliceDefaultPrimary {
    /**
     * Blog post field in *FeaturedArticle → Primary*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: featured_article.primary.blog_post
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    blog_post: prismicT.RelationField<"blog_post">;
}
/**
 * Default variation for FeaturedArticle Slice
 *
 * - **API ID**: `default`
 * - **Description**: `FeaturedArticle`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FeaturedArticleSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<FeaturedArticleSliceDefaultPrimary>, never>;
/**
 * Slice variation for *FeaturedArticle*
 *
 */
type FeaturedArticleSliceVariation = FeaturedArticleSliceDefault;
/**
 * FeaturedArticle Shared Slice
 *
 * - **API ID**: `featured_article`
 * - **Description**: `FeaturedArticle`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FeaturedArticleSlice = prismicT.SharedSlice<"featured_article", FeaturedArticleSliceVariation>;
/**
 * Primary content in Footer → Primary
 *
 */
interface FooterSliceDefaultPrimary {
    /**
     * Background Color field in *Footer → Primary*
     *
     * - **Field Type**: Color
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.primary.background_color
     * - **Documentation**: https://prismic.io/docs/core-concepts/color
     *
     */
    background_color: prismicT.ColorField;
    /**
     * Text Color field in *Footer → Primary*
     *
     * - **Field Type**: Color
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.primary.text_color
     * - **Documentation**: https://prismic.io/docs/core-concepts/color
     *
     */
    text_color: prismicT.ColorField;
    /**
     * Menu about field in *Footer → Primary*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.primary.menu_about
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    menu_about: prismicT.RelationField<"navigation_menu">;
    /**
     * Menu_seo field in *Footer → Primary*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.primary.menu_seo
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    menu_seo: prismicT.RelationField<"navigation_menu">;
    /**
     * Newsletter Header field in *Footer → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.primary.newsletter_header
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    newsletter_header: prismicT.RichTextField;
    /**
     * Newsletter description field in *Footer → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.primary.newsletter_description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    newsletter_description: prismicT.RichTextField;
    /**
     * Socials field in *Footer → Primary*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.primary.socials
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    socials: prismicT.RelationField<"socials">;
    /**
     * Input border field in *Footer → Primary*
     *
     * - **Field Type**: Color
     * - **Placeholder**: Select input border color
     * - **API ID Path**: footer.primary.input_border_color
     * - **Documentation**: https://prismic.io/docs/core-concepts/color
     *
     */
    input_border_color: prismicT.ColorField;
    /**
     * Input btn bg field in *Footer → Primary*
     *
     * - **Field Type**: Color
     * - **Placeholder**: Select the button background color
     * - **API ID Path**: footer.primary.input_btn_bg_color
     * - **Documentation**: https://prismic.io/docs/core-concepts/color
     *
     */
    input_btn_bg_color: prismicT.ColorField;
    /**
     * Input text field in *Footer → Primary*
     *
     * - **Field Type**: Color
     * - **Placeholder**: Select input text color
     * - **API ID Path**: footer.primary.input_text_input_color
     * - **Documentation**: https://prismic.io/docs/core-concepts/color
     *
     */
    input_text_input_color: prismicT.ColorField;
}
/**
 * Default variation for Footer Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Footer`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FooterSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<FooterSliceDefaultPrimary>, never>;
/**
 * Slice variation for *Footer*
 *
 */
type FooterSliceVariation = FooterSliceDefault;
/**
 * Footer Shared Slice
 *
 * - **API ID**: `footer`
 * - **Description**: `Footer`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FooterSlice = prismicT.SharedSlice<"footer", FooterSliceVariation>;
/**
 * Primary content in HomeHero → Primary
 *
 */
interface HomeHeroSliceDefaultPrimary {
    /**
     * Header field in *HomeHero → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: A nice header for your hero
     * - **API ID Path**: home_hero.primary.header
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    header: prismicT.TitleField;
    /**
     * Subtitle field in *HomeHero → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice subtitle for the homepage
     * - **API ID Path**: home_hero.primary.subheader
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    subheader: prismicT.RichTextField;
    /**
     * Video field in *HomeHero → Primary*
     *
     * - **Field Type**: Link to Media
     * - **Placeholder**: Paste link to video here...
     * - **API ID Path**: home_hero.primary.hero_video
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    hero_video: prismicT.LinkToMediaField;
    /**
     * navigation field in *HomeHero → Primary*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: home_hero.primary.navigation
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    navigation: prismicT.RelationField<"navigation">;
    /**
     * Logo field in *HomeHero → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: home_hero.primary.logo
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    logo: prismicT.ImageField<never>;
    /**
     * Opacity Color field in *HomeHero → Primary*
     *
     * - **Field Type**: Color
     * - **Placeholder**: *None*
     * - **API ID Path**: home_hero.primary.opacity_color
     * - **Documentation**: https://prismic.io/docs/core-concepts/color
     *
     */
    opacity_color: prismicT.ColorField;
    /**
     * Opacity Percentage field in *HomeHero → Primary*
     *
     * - **Field Type**: Number
     * - **Placeholder**: *None*
     * - **API ID Path**: home_hero.primary.opacity_percentage
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    opacity_percentage: prismicT.NumberField;
}
/**
 * Default variation for HomeHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: `HomeHero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HomeHeroSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<HomeHeroSliceDefaultPrimary>, never>;
/**
 * Slice variation for *HomeHero*
 *
 */
type HomeHeroSliceVariation = HomeHeroSliceDefault;
/**
 * HomeHero Shared Slice
 *
 * - **API ID**: `home_hero`
 * - **Description**: `HomeHero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HomeHeroSlice = prismicT.SharedSlice<"home_hero", HomeHeroSliceVariation>;
/**
 * Primary content in InterceptGrid → Primary
 *
 */
interface MixedGridSliceDefaultPrimary {
    /**
     * Main Article field in *InterceptGrid → Primary*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: mixed_grid.primary.main_article
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    main_article: prismicT.RelationField<"blog_post">;
    /**
     * Collection field in *InterceptGrid → Primary*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: mixed_grid.primary.collection
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    collection: prismicT.RelationField<"collection">;
    /**
     * Title field in *InterceptGrid → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: mixed_grid.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Description field in *InterceptGrid → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: mixed_grid.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismicT.KeyTextField;
}
/**
 * Item in InterceptGrid → Items
 *
 */
export interface MixedGridSliceDefaultItem {
    /**
     * Other Articles field in *InterceptGrid → Items*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: mixed_grid.items[].article
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    article: prismicT.RelationField<"blog_post">;
}
/**
 * Default variation for InterceptGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: `MixedGrid`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type MixedGridSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<MixedGridSliceDefaultPrimary>, Simplify<MixedGridSliceDefaultItem>>;
/**
 * Slice variation for *InterceptGrid*
 *
 */
type MixedGridSliceVariation = MixedGridSliceDefault;
/**
 * InterceptGrid Shared Slice
 *
 * - **API ID**: `mixed_grid`
 * - **Description**: `MixedGrid`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type MixedGridSlice = prismicT.SharedSlice<"mixed_grid", MixedGridSliceVariation>;
/**
 * Primary content in Navbar → Primary
 *
 */
interface NavbarSliceDefaultPrimary {
    /**
     * Navigation field in *Navbar → Primary*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: navbar.primary.navigation
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    navigation: prismicT.RelationField<"navigation">;
    /**
     * Logo field in *Navbar → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: navbar.primary.logo
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    logo: prismicT.ImageField<never>;
}
/**
 * Default variation for Navbar Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Navbar`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type NavbarSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<NavbarSliceDefaultPrimary>, never>;
/**
 * Slice variation for *Navbar*
 *
 */
type NavbarSliceVariation = NavbarSliceDefault;
/**
 * Navbar Shared Slice
 *
 * - **API ID**: `navbar`
 * - **Description**: `Navbar`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type NavbarSlice = prismicT.SharedSlice<"navbar", NavbarSliceVariation>;
/**
 * Primary content in TopStory → Primary
 *
 */
interface TopStorySliceDefaultPrimary {
    /**
     * Main article field in *TopStory → Primary*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: top_story.primary.main_article
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    main_article: prismicT.RelationField<"blog_post">;
    /**
     * Title field in *TopStory → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Enter the section's title
     * - **API ID Path**: top_story.primary.section_title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    section_title: prismicT.KeyTextField;
}
/**
 * Item in TopStory → Items
 *
 */
export interface TopStorySliceDefaultItem {
    /**
     * Other articles (4 max) field in *TopStory → Items*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: top_story.items[].other_articles
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    other_articles: prismicT.RelationField<"blog_post">;
}
/**
 * Default variation for TopStory Slice
 *
 * - **API ID**: `default`
 * - **Description**: `TopStory`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TopStorySliceDefault = prismicT.SharedSliceVariation<"default", Simplify<TopStorySliceDefaultPrimary>, Simplify<TopStorySliceDefaultItem>>;
/**
 * Slice variation for *TopStory*
 *
 */
type TopStorySliceVariation = TopStorySliceDefault;
/**
 * TopStory Shared Slice
 *
 * - **API ID**: `top_story`
 * - **Description**: `TopStory`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TopStorySlice = prismicT.SharedSlice<"top_story", TopStorySliceVariation>;
/**
 * Primary content in VanityHero → Primary
 *
 */
interface VanityHeroSliceDefaultPrimary {
    /**
     * Main article field in *VanityHero → Primary*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: vanity_hero.primary.main_article
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    main_article: prismicT.RelationField<"blog_post">;
    /**
     * Social Posts (4 posts) field in *VanityHero → Primary*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: vanity_hero.primary.social_posts
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    social_posts: prismicT.RelationField<"vanitysocialposts">;
    /**
     * Socials Accounts field in *VanityHero → Primary*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: vanity_hero.primary.socials_accounts
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    socials_accounts: prismicT.RelationField<"socials">;
    /**
     * Promo field in *VanityHero → Primary*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: vanity_hero.primary.promo
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    promo: prismicT.RelationField<"vanity_sponsoring">;
}
/**
 * Item in VanityHero → Items
 *
 */
export interface VanityHeroSliceDefaultItem {
    /**
     * Trending articles (3 articles) field in *VanityHero → Items*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: vanity_hero.items[].trending_articles
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    trending_articles: prismicT.RelationField<"blog_post">;
    /**
     * Other articles (2 articles) field in *VanityHero → Items*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: vanity_hero.items[].other_articles
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    other_articles: prismicT.RelationField<"blog_post">;
}
/**
 * Default variation for VanityHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: `VanityHero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type VanityHeroSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<VanityHeroSliceDefaultPrimary>, Simplify<VanityHeroSliceDefaultItem>>;
/**
 * Slice variation for *VanityHero*
 *
 */
type VanityHeroSliceVariation = VanityHeroSliceDefault;
/**
 * VanityHero Shared Slice
 *
 * - **API ID**: `vanity_hero`
 * - **Description**: `VanityHero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type VanityHeroSlice = prismicT.SharedSlice<"vanity_hero", VanityHeroSliceVariation>;
/**
 * Primary content in VideoHero → Primary
 *
 */
interface VideoHeroSliceDefaultPrimary {
    /**
     * Video field in *VideoHero → Primary*
     *
     * - **Field Type**: Link to Media
     * - **Placeholder**: *None*
     * - **API ID Path**: video_hero.primary.video
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    video: prismicT.LinkToMediaField;
    /**
     * Blog post field in *VideoHero → Primary*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: video_hero.primary.blog_post
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    blog_post: prismicT.RelationField;
    /**
     * Title field in *VideoHero → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: video_hero.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Subtitle field in *VideoHero → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: video_hero.primary.subtitle
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    subtitle: prismicT.KeyTextField;
    /**
     * CTA field in *VideoHero → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: video_hero.primary.cta
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    cta: prismicT.KeyTextField;
    /**
     * Show down arrow field in *VideoHero → Primary*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: video_hero.primary.show_down_arrow
     * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
     *
     */
    show_down_arrow: prismicT.BooleanField;
}
/**
 * Default variation for VideoHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: `VideoHero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type VideoHeroSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<VideoHeroSliceDefaultPrimary>, never>;
/**
 * Slice variation for *VideoHero*
 *
 */
type VideoHeroSliceVariation = VideoHeroSliceDefault;
/**
 * VideoHero Shared Slice
 *
 * - **API ID**: `video_hero`
 * - **Description**: `VideoHero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type VideoHeroSlice = prismicT.SharedSlice<"video_hero", VideoHeroSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { AuthorDocumentData, AuthorDocument, BlogPostDocumentData, BlogPostDocument, CollectionDocumentData, CollectionDocument, FooterDocumentData, FooterDocumentDataSlicesSlice, FooterDocument, HomepageDocumentData, HomepageDocumentDataSlicesSlice, HomepageDocument, NavbarDocumentData, NavbarDocumentDataSlicesSlice, NavbarDocument, NavigationMenuDocumentData, NavigationMenuDocumentDataMenuItem, NavigationMenuDocument, NavigationDocumentData, NavigationDocumentDataNavigationItemItem, NavigationDocument, PageDocumentData, PageDocument, SocialsDocumentData, SocialsDocumentDataMediaInfoItem, SocialsDocument, VanitySponsoringDocumentData, VanitySponsoringDocument, VanitysocialpostsDocumentData, VanitysocialpostsDocumentDataPostItem, VanitysocialpostsDocumentDataSlicesSlice, VanitysocialpostsDocument, AllDocumentTypes, CollectionGridSliceDefaultPrimary, CollectionGridSliceDefault, CollectionGridSliceVariation, CollectionGridSlice, CollectionSliderSliceDefaultPrimary, CollectionSliderSliceDefaultItem, CollectionSliderSliceDefault, CollectionSliderSliceVariation, CollectionSliderSlice, FeaturedArticleSliceDefaultPrimary, FeaturedArticleSliceDefault, FeaturedArticleSliceVariation, FeaturedArticleSlice, FooterSliceDefaultPrimary, FooterSliceDefault, FooterSliceVariation, FooterSlice, HomeHeroSliceDefaultPrimary, HomeHeroSliceDefault, HomeHeroSliceVariation, HomeHeroSlice, MixedGridSliceDefaultPrimary, MixedGridSliceDefaultItem, MixedGridSliceDefault, MixedGridSliceVariation, MixedGridSlice, NavbarSliceDefaultPrimary, NavbarSliceDefault, NavbarSliceVariation, NavbarSlice, TopStorySliceDefaultPrimary, TopStorySliceDefaultItem, TopStorySliceDefault, TopStorySliceVariation, TopStorySlice, VanityHeroSliceDefaultPrimary, VanityHeroSliceDefaultItem, VanityHeroSliceDefault, VanityHeroSliceVariation, VanityHeroSlice, VideoHeroSliceDefaultPrimary, VideoHeroSliceDefault, VideoHeroSliceVariation, VideoHeroSlice };
    }
}
