// Code generated by Slice Machine. DO NOT EDIT.

import ArticleCarousel from './ArticleCarousel';
import CollectionCarousel from './CollectionCarousel';
import Footer from './Footer';
import HomeHero from './HomeHero';
import MixedGrid from './MixedGrid';
import Navbar from './Navbar';
import PromotionBanner from './PromotionBanner';
import SeoSection from './SeoSection';

export {
	ArticleCarousel,
	CollectionCarousel,
	Footer,
	HomeHero,
	MixedGrid,
	Navbar,
	PromotionBanner,
	SeoSection,
};

export const components = {
	article_carousel: ArticleCarousel,
	home_collection: CollectionCarousel,
	footer: Footer,
	home_hero: HomeHero,
	mixed_grid: MixedGrid,
	navbar: Navbar,
	promotion_banner: PromotionBanner,
	seo_section: SeoSection,
};
