// Code generated by Slice Machine. DO NOT EDIT.

import ArticleCarousel from './ArticleCarousel';
import ArticleCarouselV2 from './ArticleCarouselV2';
import CollectionCarousel from './CollectionCarousel';
import Footer from './Footer';
import HomeHero from './HomeHero';
import PromotionBanner from './PromotionBanner';
import SeoSection from './SeoSection';

export {
	ArticleCarousel,
	ArticleCarouselV2,
	CollectionCarousel,
	Footer,
	HomeHero,
	PromotionBanner,
	SeoSection,
};

export const components = {
	article_carousel: ArticleCarousel,
	article_carousel_v2: ArticleCarouselV2,
	home_collection: CollectionCarousel,
	footer: Footer,
	home_hero: HomeHero,
	promotion_banner: PromotionBanner,
	seo_section: SeoSection,
};
