// Code generated by Slice Machine. DO NOT EDIT.

import ArticleCarousel from './ArticleCarousel';
import HomeCollection from './HomeCollection';
import HomeHero from './HomeHero';

export {
	ArticleCarousel,
	HomeCollection,
	HomeHero,
};

export const components = {
	article_carousel: ArticleCarousel,
	home_collection: HomeCollection,
	home_hero: HomeHero,
};
